AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Alias Switcher API written with SpringBoot with the aws-serverless-java-container library

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  aliasSwitcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.adam.aliasswitcher.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/alias-switcher-0.0.1-SNAPSHOT-lambda-package.zip
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  Auth:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/authenticate'
    Export:
      Name: Auth
  Aliases:
    Description: URL for Aliases
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/api/v1/aliases'
    Export:
      Name: Aliases
